### ISSUE TITLE
Missing annotation for toctree contains reference to nonexisting document 

### ISSUE THREAD

**Issue by mloskot** [ammaraskar/sphinx-action#4]
I'm testing the sphinx-action and I noticed that if a there is non-existing document added to toctree, then annotation is missing.

First, the problem `toctree contains reference to nonexisting document 'drivers'` is listed:

![image](https://user-images.githubusercontent.com/80741/71041984-cd9a3580-212a-11ea-9be3-7559cb8d2ca0.png)

Next, I click on `Check warning on line 7 in project/doc/index.rst` and it gets me to here:

![image](https://user-images.githubusercontent.com/80741/71042030-f1f61200-212a-11ea-8b3d-c0e3f6843077.png)

As you can see, there is only the annotation for the `Unknown directive type "whoops"` issue, but none for the `toctree contains reference to nonexisting document 'drivers'`

**Comment by ammaraskar** [comment]
Sorry for the late reply.

This is bizarre, I think this is a bug in Github's annotations and not on my end. Initially I thought it might be because `index.rst` wasn't changed in that commit, so it can't show it, but if we look at https://github.com/mloskot/github-actions-test/runs/353532893 and try to click through there, it doesn't show up either. However, the annotation is clearly there as it shows on the actions GUI and through the API.

**Comment by mloskot** [comment]
I think you're right and this may be GitHub Actions bug. Well, I don't know where to report a bug, perhaps it should be discussed at https://github.community/t5/GitHub-Actions/bd-p/actions, but I'm not sure what details to include. So, closing this.
