### ISSUE TITLE
Action fails with due to missing log file

### ISSUE THREAD

**Issue by cmouse** [ammaraskar/sphinx-action#5]
Version: 0.1

https://github.com/cmouse/dovecot-documentation/commit/95de65dc80bf4cf3ddbf57a3f0e1fc0c6fab4f9a/checks?check_suite_id=368217245

The build fails because it cannot find some sphinx log file. There is no indication anywhere how it should be created?

**Comment by ammaraskar** [comment]
Sorry for the late reply. Would you mind giving the latest version a shot? The sphinx log is needed to parse the errors and if the docs build successfully (which they seem like they do in your logs), then it should exist.

**Comment by ocket8888** [comment]
I'm pinned to action version `@master` and have the same issue:
```
====================================
Building docs in docs/
====================================
Traceback (most recent call last):
  File "/entrypoint.py", line 27, in <module>
    action.build_all_docs(github_env, [os.environ.get('INPUT_DOCS-FOLDER')])
  File "/sphinx_action/action.py", line 137, in build_all_docs
    return_code, annotations = build_docs(
  File "/sphinx_action/action.py", line 112, in build_docs
    with open(log_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'
```

**Comment by cmouse** [comment]
> Sorry for the late reply. Would you mind giving the latest version a shot? The sphinx log is needed to parse the errors and if the docs build successfully (which they seem like they do in your logs), then it should exist.

Sorry for not replying, I can try this again after next week.

**Comment by Enderdead** [comment]
I've figured out the problem. The issue is due to a problem with argument passing. When you use the default build cmd (`make`), the build call is this one : 

https://github.com/ammaraskar/sphinx-action/blob/3dd694e9195d6967845dd6d9832f46d879aeb790/sphinx_action/action.py#L100-L105

In this manner, you pass the `-w '/tmp/sphinx-log'` argument as an env var.
But in general, your make file looks like this :  
```
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```
This script doesn't take into account your env var so the log file won't be generated.

An easy way to fix that is to use a custom build cmd like this one: `build-command: "sphinx-build source build"`.

Because in this case, the action script will execute this line.
https://github.com/ammaraskar/sphinx-action/blob/3dd694e9195d6967845dd6d9832f46d879aeb790/sphinx_action/action.py#L107-L110

Sphinx option will be hard written in the command.

**Comment by ocket8888** [comment]
If I'm understanding this right another solution is to replace our current sphinx options e.g. `SPHINXOPTS = --foo` with an additive assignment like `SPHINXOPTS += --foo`

**Comment by Enderdead** [comment]
I've just tested your solution and it works! Just add a plus before the equals like this : 
```
SPHINXOPTS    +=
```
That doesn't matter if the right side is empty.

**Comment by cmouse** [comment]
> If I'm understanding this right another solution is to replace our current sphinx options e.g. `SPHINXOPTS = --foo` with an additive assignment like `SPHINXOPTS += --foo`

Wonder if this should be upstreamed?

**Comment by novski** [comment]
Tested, and can confirm the additive assignment worked in my case as well.
Got to your `YOUR-GITHUB-USER/REPO-NAME/docs/Makefile and change Line 5 to `SPHINXOPTS    +=                     `like [in my case](https://github.com/novski/sphinx-test4/blob/230845adec229bb43aad4b95e40906d8611a123e/docs/Makefile#L5).

**Comment by iguessthislldo** [comment]
> Wonder if this should be upstreamed?

If not I think the README should at least make note of it.

**Comment by ammaraskar** [comment]
Apologies for the late response, thanks for investigating this everyone.

If you take a look at my test projects here: https://github.com/ammaraskar/sphinx-action/blob/3dd694e9195d6967845dd6d9832f46d879aeb790/tests/test_projects/no_errors/Makefile#L1-L9

They seem to be setup so that they support overriding through environment variables. Maybe this is a change in newer version of sphinx. The intention with this project was to just have it be drop-in without having the user make any changes to their sphinx stuff, let me see if I can find a more versatile way to achieve this.

**Comment by ammaraskar** [comment]
Could someone try with the origin Makefile and the action pinned to master? I think this commit should help:

https://github.com/ammaraskar/sphinx-action/commit/1983868b92093bed61a91ac46eaa2d173d897872

**Comment by Enderdead** [comment]
Tested on my own project. Everything looks fine. Good job!
You can review this at this repo: https://github.com/Enderdead/pyLambdaFlows/tree/TestSphinxAction

**Comment by ammaraskar** [comment]
Feel free to re-open if anyone finds the latest release doesn't work with their original Makefiles.

**Comment by Narayana-Rao** [comment]
Facing the log file issue even after updating make file.

[sphinx-action] Running: ['sphinx-build', '-b', 'html', '--keep-going', '--no-color', '-w', '/tmp/sphinx-log']
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 152, in build_all_docs
    return_code, annotations = build_docs(github_env.build_command, docs_dir)
  File "/sphinx_action/action.py", line 134, in build_docs
    with open(log_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'

**Comment by ammaraskar** [comment]
Your build is failing for a different reason:

```
usage: sphinx-build [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-build: error: the following arguments are required: sourcedir, outputdir, filenames
```

The build command doesn't have a source folder specified as you can see from the "Running:" line. Your  `build-command` should look instead like `sphinx-build . -b html`, notice the dot representing the current directory.

**Comment by Narayana-Rao** [comment]
Thank you. But, still the same error

====================================
Building docs in help/
====================================
[sphinx-action] Running: ['sphinx-build', '.', '-b', 'html', '--keep-going', '--no-color', '-w', '/tmp/sphinx-log']
    with open(log_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'

**Comment by DominiqueMakowski** [comment]
Hi, I am still encountering the same issue: 

```
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 152, in build_all_docs
    return_code, annotations = build_docs(github_env.build_command, docs_dir)
  File "/sphinx_action/action.py", line 134, in build_docs
    with open(log_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'
```

Note that at the end of the log it says:

```
[sphinx-action] Running: ['sphinx-build', '-b', 'html', '.', '_build', '--keep-going', '--no-color', '-w', '/tmp/sphinx-log']
```

How can I modify the last argument?

when building the documentation using the action and [this](https://github.com/neuropsychology/NeuroKit/blob/2f62885808601576f58c72e4bd406999ebfe530b/.github/workflows/docs-build.yml#L33) command:

`sphinx-build -b html . _build`

**Comment by ocket8888** [comment]
Looks like your build command is missing the `-w /tmp/sphinx-log` argument

**Comment by pmilano1** [comment]
Is this still an issue for anyone else? I get it with -

`name: "Generate Documentation"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html docsrc/ _build -f /tmp/sphinx.log "
        docs-folder: "docs/"`

I use the modified Makefile

`# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SOURCEDIR     = .
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)`

**Comment by ocket8888** [comment]
Your Makefile seems irrelevant, it doesn't look to be using that.

The output of the runner shows a different build command than the one you specified. Are you sure that it's using the configuration you posted? You also seem to be using `-f /tmp/sphinx-log` instead of/in addition to `-w /tmp/sphinx-log`.

At any rate, this issue is about builders that use `make`, so your problem is probably unrelated.

**Comment by Claudio9701** [comment]
I was having the same missing log file error, none of the above worked. The solution was to add this lines to my `docs/requirements.txt`

```
sphinx>=6.1.3
docutils>=0.19
```

**Comment by SoundsSerious** [comment]
@Claudio9701 +1 for this
